export const LANGUAGES = [
  { code: "en", name: "English", native: "English" },
  { code: "es", name: "Spanish", native: "Español" },
  { code: "fr", name: "French", native: "Français" },
  { code: "de", name: "German", native: "Deutsch" },
] as const;

export type Locale = (typeof LANGUAGES)[number]["code"];
export const LOCALIZED = LANGUAGES.filter((l) => l.code !== "en");

export const copy: Record<Locale, {
  homeTitle: string; homeDescription: string; intro: string; solve3: string; solve2: string;
  notation: string; timer: string; home: string; learn: string; tools: string;
  notationTitle: string; notationDescription: string; timerTitle: string; timerDescription: string;
  solver3Title: string; solver2Title: string; solver3Description: string; solver2Description: string;
}> = {
  en: { homeTitle: "Rubik's Cube Solver – Free Online 2x2 & 3x3 Solver | RubikSolver", homeDescription: "Solve your 2x2 or 3x3 Rubik's Cube online with step-by-step moves, clear notation, and interactive guidance.", intro: "Enter your cube's colors and RubikSolver builds a clear solution for your scramble.", solve3: "Solve 3x3", solve2: "Solve 2x2", notation: "Notation", timer: "Timer", home: "Home", learn: "Learn", tools: "Tools", notationTitle: "Rubik's Cube Move Notation", notationDescription: "Learn Rubik's Cube notation with visual guides for R, L, U, D, F, B, prime, and double moves.", timerTitle: "Rubik's Cube Timer", timerDescription: "Practice 2x2 and 3x3 solves with a free online Rubik's Cube timer, scramble generator, solve history, averages, and Ao5.", solver3Title: "3x3 Rubik's Cube Solver", solver2Title: "2x2 Rubik's Cube Solver", solver3Description: "Solve a 3x3 Rubik's Cube online. Enter your cube's colors and follow the solution move by move.", solver2Description: "Solve a 2x2 Rubik's Cube online. Enter your cube's colors and follow a clear step-by-step solution." },
  es: { homeTitle: "Solucionador de Cubo de Rubik – 2x2 y 3x3 Gratis | RubikSolver", homeDescription: "Resuelve tu Cubo de Rubik 2x2 o 3x3 en línea con pasos claros, notación de movimientos y orientación interactiva.", intro: "Introduce los colores de tu cubo y RubikSolver genera una solución clara para tu mezcla.", solve3: "Resolver 3x3", solve2: "Resolver 2x2", notation: "Notación", timer: "Temporizador", home: "Inicio", learn: "Aprender", tools: "Herramientas", notationTitle: "Notación de movimientos del Cubo de Rubik", notationDescription: "Aprende la notación del Cubo de Rubik con guías visuales para R, L, U, D, F, B y los giros inversos y dobles.", timerTitle: "Temporizador de Cubo de Rubik", timerDescription: "Practica con cubos 2x2 y 3x3 usando un temporizador gratuito, generador de mezclas, historial, promedios y Ao5.", solver3Title: "Solucionador de Cubo de Rubik 3x3", solver2Title: "Solucionador de Cubo de Rubik 2x2", solver3Description: "Resuelve un Cubo de Rubik 3x3 en línea. Introduce los colores y sigue la solución movimiento a movimiento.", solver2Description: "Resuelve un Cubo de Rubik 2x2 en línea. Introduce los colores y sigue una solución clara paso a paso." },
  fr: { homeTitle: "Solveur de Rubik's Cube – 2x2 et 3x3 Gratuit en Ligne | RubikSolver", homeDescription: "Résolvez votre Rubik's Cube 2x2 ou 3x3 en ligne avec des étapes claires, la notation des mouvements et un guidage interactif.", intro: "Indiquez les couleurs de votre cube et RubikSolver génère une solution claire adaptée à votre mélange.", solve3: "Résoudre le 3x3", solve2: "Résoudre le 2x2", notation: "Notation", timer: "Chronomètre", home: "Accueil", learn: "Apprendre", tools: "Outils", notationTitle: "Notation des mouvements du Rubik's Cube", notationDescription: "Apprenez la notation du Rubik's Cube grâce à des guides visuels pour R, L, U, D, F, B et les mouvements inverses et doubles.", timerTitle: "Chronomètre de Rubik's Cube", timerDescription: "Entraînez-vous au 2x2 et au 3x3 avec un chronomètre gratuit, un générateur de mélanges, un historique, des moyennes et un Ao5.", solver3Title: "Solveur de Rubik's Cube 3x3", solver2Title: "Solveur de Rubik's Cube 2x2", solver3Description: "Résolvez un Rubik's Cube 3x3 en ligne. Indiquez les couleurs et suivez la solution mouvement par mouvement.", solver2Description: "Résolvez un Rubik's Cube 2x2 en ligne. Indiquez les couleurs et suivez une solution claire, étape par étape." },
  de: { homeTitle: "Rubik's Cube Löser – Kostenloser Online-Löser für 2x2 & 3x3 | RubikSolver", homeDescription: "Löse deinen 2x2- oder 3x3-Rubik's Cube online mit klaren Schritt-für-Schritt-Zügen, Notation und interaktiver Anleitung.", intro: "Gib die Farben deines Würfels ein und RubikSolver erstellt eine klare Lösung für deinen Scramble.", solve3: "3x3 lösen", solve2: "2x2 lösen", notation: "Notation", timer: "Timer", home: "Startseite", learn: "Lernen", tools: "Werkzeuge", notationTitle: "Rubik's Cube Zugnotation", notationDescription: "Lerne die Rubik's Cube-Notation mit visuellen Erklärungen für R, L, U, D, F, B sowie inverse und doppelte Züge.", timerTitle: "Rubik's Cube Timer", timerDescription: "Trainiere 2x2- und 3x3-Lösungen mit einem kostenlosen Online-Timer, Scramble-Generator, Lösungsverlauf, Durchschnittswerten und Ao5.", solver3Title: "3x3 Rubik's Cube Löser", solver2Title: "2x2 Rubik's Cube Löser", solver3Description: "Löse einen 3x3-Rubik's Cube online. Gib die Farben ein und führe die Lösung Zug für Zug aus.", solver2Description: "Löse einen 2x2-Rubik's Cube online. Gib die Farben ein und folge einer klaren Schritt-für-Schritt-Lösung." },
};
