export const LANGUAGES = [
  { code: "en", name: "English", native: "English" },
  { code: "hi", name: "Hindi", native: "हिन्दी" },
  { code: "zh", name: "Chinese", native: "中文" },
  { code: "es", name: "Spanish", native: "Español" },
  { code: "ar", name: "Arabic", native: "العربية" },
  { code: "pt", name: "Portuguese", native: "Português" },
  { code: "de", name: "German", native: "Deutsch" },
  { code: "ru", name: "Russian", native: "Русский" },
  { code: "fr", name: "French", native: "Français" },
  { code: "ja", name: "Japanese", native: "日本語" },
] as const;

export type Locale = (typeof LANGUAGES)[number]["code"];
export const LOCALIZED = LANGUAGES.filter((l) => l.code !== "en");

export const copy: Record<Exclude<Locale, "en">, {
  homeTitle: string; homeDescription: string; intro: string; solve3: string; solve2: string;
  notation: string; timer: string; home: string; learn: string; tools: string;
  notationTitle: string; notationDescription: string; timerTitle: string; timerDescription: string;
  solver3Title: string; solver2Title: string; solver3Description: string; solver2Description: string;
}> = {
  hi: { homeTitle: "RubikSolver — 2x2 और 3x3 रूबिक क्यूब सॉल्वर", homeDescription: "2x2 या 3x3 रूबिक क्यूब को हल करना सीखें और हर चाल को आसान, चरण-दर-चरण निर्देशों के साथ पूरा करें।", intro: "अपने क्यूब के रंग दर्ज करें और RubikSolver आपकी स्थिति के लिए चालों का स्पष्ट समाधान तैयार करेगा।", solve3: "3x3 हल करें", solve2: "2x2 हल करें", notation: "नोटेशन", timer: "टाइमर", home: "होम", learn: "सीखें", tools: "टूल्स", notationTitle: "रूबिक क्यूब मूव नोटेशन", notationDescription: "R, L, U, D, F और B जैसी रूबिक क्यूब चालों और उनके प्राइम व डबल टर्न को समझें।", timerTitle: "RubikSolver क्यूब टाइमर", timerDescription: "2x2 और 3x3 अभ्यास के लिए आधुनिक रूबिक क्यूब स्पीड टाइमर और स्क्रैम्बलर।", solver3Title: "3x3 रूबिक क्यूब सॉल्वर", solver2Title: "2x2 रूबिक क्यूब सॉल्वर", solver3Description: "3x3 क्यूब को कैसे हल करें? अपने रंग दर्ज करें और समाधान को एक-एक चाल करके पूरा करें।", solver2Description: "2x2 क्यूब को कैसे हल करें? अपने रंग दर्ज करें और आसान चरणों में समाधान देखें।" },
  zh: { homeTitle: "RubikSolver — 2x2 和 3x3 魔方在线求解器", homeDescription: "学习如何还原 2x2 或 3x3 魔方，并按照清晰的逐步指引完成每一步。", intro: "输入魔方的颜色状态，RubikSolver 会为你的打乱生成清晰的还原步骤。", solve3: "求解 3x3", solve2: "求解 2x2", notation: "公式符号", timer: "计时器", home: "首页", learn: "学习", tools: "工具", notationTitle: "魔方公式符号说明", notationDescription: "了解 R、L、U、D、F、B 等魔方转动符号，以及逆时针和双层转动的写法。", timerTitle: "RubikSolver 魔方计时器", timerDescription: "用于 2x2 和 3x3 练习的现代魔方速拧计时器和打乱生成器。", solver3Title: "3x3 魔方在线求解器", solver2Title: "2x2 魔方在线求解器", solver3Description: "想知道 3x3 魔方怎么还原？输入颜色，按照生成的步骤逐步完成。", solver2Description: "想知道 2x2 魔方怎么还原？输入颜色，查看简单清晰的还原步骤。" },
  es: { homeTitle: "RubikSolver — Solucionador de cubo Rubik 2x2 y 3x3", homeDescription: "Aprende a resolver un cubo Rubik 2x2 o 3x3 con instrucciones claras paso a paso.", intro: "Introduce los colores de tu cubo y RubikSolver generará una solución clara para tu mezcla.", solve3: "Resolver 3x3", solve2: "Resolver 2x2", notation: "Notación", timer: "Temporizador", home: "Inicio", learn: "Aprender", tools: "Herramientas", notationTitle: "Notación del cubo Rubik", notationDescription: "Aprende los movimientos R, L, U, D, F y B del cubo Rubik, incluidos los giros inversos y dobles.", timerTitle: "Temporizador de cubo Rubik — RubikSolver", timerDescription: "Temporizador de velocidad y generador de mezclas para practicar con cubos 2x2 y 3x3.", solver3Title: "Solucionador de cubo Rubik 3x3", solver2Title: "Solucionador de cubo Rubik 2x2", solver3Description: "¿Cómo resolver un cubo 3x3? Introduce los colores y sigue la solución movimiento a movimiento.", solver2Description: "¿Cómo resolver un cubo 2x2? Introduce los colores y sigue una solución sencilla paso a paso." },
  ar: { homeTitle: "RubikSolver — حل مكعب روبيك 2x2 و3x3", homeDescription: "تعلّم كيفية حل مكعب روبيك 2x2 أو 3x3 باتباع خطوات واضحة وسهلة.", intro: "أدخل ألوان مكعبك وسيُنشئ RubikSolver حلاً واضحاً لحالته الحالية.", solve3: "حل 3x3", solve2: "حل 2x2", notation: "الترميز", timer: "المؤقت", home: "الرئيسية", learn: "تعلّم", tools: "الأدوات", notationTitle: "ترميز حركات مكعب روبيك", notationDescription: "تعرّف على رموز الحركات R وL وU وD وF وB، بما في ذلك الحركات العكسية والدوران المزدوج.", timerTitle: "مؤقت مكعب روبيك — RubikSolver", timerDescription: "مؤقت سرعة ومولّد خلط حديث للتدرب على مكعبي 2x2 و3x3.", solver3Title: "حل مكعب روبيك 3x3", solver2Title: "حل مكعب روبيك 2x2", solver3Description: "كيف تحل مكعب 3x3؟ أدخل الألوان واتبع الحل خطوة بخطوة.", solver2Description: "كيف تحل مكعب 2x2؟ أدخل الألوان واتبع الحل بطريقة بسيطة خطوة بخطوة." },
  pt: { homeTitle: "RubikSolver — Solucionador de cubo mágico 2x2 e 3x3", homeDescription: "Aprenda a resolver um cubo mágico 2x2 ou 3x3 com instruções claras e passo a passo.", intro: "Informe as cores do seu cubo e o RubikSolver gera uma solução clara para a mistura.", solve3: "Resolver 3x3", solve2: "Resolver 2x2", notation: "Notação", timer: "Cronômetro", home: "Início", learn: "Aprender", tools: "Ferramentas", notationTitle: "Notação do cubo mágico", notationDescription: "Aprenda os movimentos R, L, U, D, F e B do cubo mágico, incluindo giros inversos e duplos.", timerTitle: "Cronômetro de cubo mágico — RubikSolver", timerDescription: "Cronômetro de velocidade e gerador de embaralhamentos para praticar 2x2 e 3x3.", solver3Title: "Solucionador de cubo mágico 3x3", solver2Title: "Solucionador de cubo mágico 2x2", solver3Description: "Como resolver um cubo 3x3? Informe as cores e siga a solução movimento por movimento.", solver2Description: "Como resolver um cubo 2x2? Informe as cores e siga uma solução simples passo a passo." },
  de: { homeTitle: "RubikSolver — Rubik-Würfel-Löser für 2x2 und 3x3", homeDescription: "Lerne, einen 2x2- oder 3x3-Rubik-Würfel mit klaren Schritt-für-Schritt-Anweisungen zu lösen.", intro: "Gib die Farben deines Würfels ein und RubikSolver erstellt eine verständliche Lösung für deinen Scramble.", solve3: "3x3 lösen", solve2: "2x2 lösen", notation: "Notation", timer: "Timer", home: "Startseite", learn: "Lernen", tools: "Werkzeuge", notationTitle: "Rubik-Würfel-Notation", notationDescription: "Lerne die Zugnotation R, L, U, D, F und B sowie inverse und doppelte Züge.", timerTitle: "Rubik-Würfel-Timer — RubikSolver", timerDescription: "Moderner Speedtimer und Scrambler für das Training mit 2x2 und 3x3.", solver3Title: "3x3 Rubik-Würfel-Löser", solver2Title: "2x2 Rubik-Würfel-Löser", solver3Description: "Wie löst man einen 3x3-Würfel? Gib die Farben ein und folge der Lösung Zug für Zug.", solver2Description: "Wie löst man einen 2x2-Würfel? Gib die Farben ein und folge einer einfachen Schritt-für-Schritt-Lösung." },
  ru: { homeTitle: "RubikSolver — решение кубика Рубика 2x2 и 3x3", homeDescription: "Научитесь собирать кубик Рубика 2x2 или 3x3 с понятными пошаговыми инструкциями.", intro: "Введите цвета своего кубика, и RubikSolver построит понятное решение для вашей позиции.", solve3: "Решить 3x3", solve2: "Решить 2x2", notation: "Обозначения", timer: "Таймер", home: "Главная", learn: "Обучение", tools: "Инструменты", notationTitle: "Обозначения ходов кубика Рубика", notationDescription: "Разберитесь в обозначениях R, L, U, D, F и B, включая обратные и двойные повороты.", timerTitle: "Таймер кубика Рубика — RubikSolver", timerDescription: "Современный спидкубинг-таймер и генератор скрамблов для тренировок 2x2 и 3x3.", solver3Title: "Решение кубика Рубика 3x3", solver2Title: "Решение кубика Рубика 2x2", solver3Description: "Как собрать кубик 3x3? Введите цвета и выполняйте решение по одному ходу.", solver2Description: "Как собрать кубик 2x2? Введите цвета и следуйте простой пошаговой инструкции." },
  fr: { homeTitle: "RubikSolver — solveur de Rubik's Cube 2x2 et 3x3", homeDescription: "Apprenez à résoudre un Rubik's Cube 2x2 ou 3x3 grâce à des instructions claires, étape par étape.", intro: "Indiquez les couleurs de votre cube et RubikSolver génère une solution adaptée à votre mélange.", solve3: "Résoudre le 3x3", solve2: "Résoudre le 2x2", notation: "Notation", timer: "Chronomètre", home: "Accueil", learn: "Apprendre", tools: "Outils", notationTitle: "Notation du Rubik's Cube", notationDescription: "Apprenez les mouvements R, L, U, D, F et B, ainsi que les mouvements inverses et les demi-tours.", timerTitle: "Chronomètre Rubik's Cube — RubikSolver", timerDescription: "Chronomètre de speedcubing et générateur de mélanges pour vous entraîner au 2x2 et au 3x3.", solver3Title: "Solveur de Rubik's Cube 3x3", solver2Title: "Solveur de Rubik's Cube 2x2", solver3Description: "Comment résoudre un Rubik's Cube 3x3 ? Entrez les couleurs et suivez la solution mouvement par mouvement.", solver2Description: "Comment résoudre un Rubik's Cube 2x2 ? Entrez les couleurs et suivez une solution simple étape par étape." },
  ja: { homeTitle: "RubikSolver — 2x2・3x3 ルービックキューブ解法", homeDescription: "2x2・3x3ルービックキューブの揃え方を、わかりやすい手順で学べます。", intro: "キューブの色を入力すると、RubikSolverが現在の状態に合わせた解法をわかりやすく表示します。", solve3: "3x3を解く", solve2: "2x2を解く", notation: "記法", timer: "タイマー", home: "ホーム", learn: "学ぶ", tools: "ツール", notationTitle: "ルービックキューブの記法", notationDescription: "R・L・U・D・F・Bなどの基本的な回転記号と、逆回転・180度回転の読み方を解説します。", timerTitle: "ルービックキューブ タイマー — RubikSolver", timerDescription: "2x2・3x3の練習に使える、シンプルでモダンなスピードタイマーとスクランブル生成機能です。", solver3Title: "3x3ルービックキューブ解法", solver2Title: "2x2ルービックキューブ解法", solver3Description: "3x3の揃え方を知りたいですか？色を入力して、生成された手順を1手ずつ進めましょう。", solver2Description: "2x2の揃え方を知りたいですか？色を入力して、シンプルな手順で解いていきましょう。" },
};

export function localeLinks() { return LANGUAGES.map((l) => ({ ...l, href: l.code === "en" ? "/" : `/${l.code}/` })); }
