import { createFileRoute, Link, notFound } from "@tanstack/react-router";
import { ArrowLeft, Clock3, RotateCw } from "lucide-react";
import { copy, LANGUAGES, type Locale } from "@/lib/i18n";

export const Route = createFileRoute("/$lang")({
  loader: ({ params }) => { const lang = params.lang as Locale; if (!copy[lang]) throw notFound(); return { lang, c: copy[lang] }; },
  head: ({ loaderData }) => { if (!loaderData) return { meta: [{ name: "robots", content: "noindex" }] }; const { lang, c } = loaderData; return { meta: [{ title: c.homeTitle }, { name: "description", content: c.homeDescription }, ...LANGUAGES.filter(x => x.code !== lang).map(x => ({ tagName: "link", rel: "alternate", hrefLang: x.code, href: `/${x.code}/` }))] }; },
  component: LocalizedHome,
});

function Header({ lang, c }: { lang: Locale; c: typeof copy[Exclude<Locale,"en">] }) {
  return <header className="sticky top-0 z-20 border-b border-border/70 bg-background/85 backdrop-blur"><div className="mx-auto flex w-full max-w-6xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><Link to={`/${lang}/` as any} className="font-display text-lg font-semibold tracking-tight">Rubik<span className="text-primary">Solver</span></Link><nav className="hidden items-center gap-1 text-sm sm:flex"><Link to={`/${lang}/` as any} className="rounded-lg px-3 py-1.5 text-muted-foreground hover:text-foreground">{c.home}</Link><Link to={`/${lang}/notation` as any} className="rounded-lg px-3 py-1.5 text-muted-foreground hover:text-foreground">{c.notation}</Link><Link to={`/${lang}/timer` as any} className="rounded-lg px-3 py-1.5 text-muted-foreground hover:text-foreground">{c.timer}</Link></nav><LanguageSelect lang={lang} /></div></header>;
}
function LanguageSelect({ lang }: { lang: Locale }) { return <select aria-label="Language" value={lang} onChange={e => { window.location.href = `/${e.target.value}/`; }} className="rounded-lg border border-border bg-background px-2.5 py-1.5 text-sm">{LANGUAGES.map(l => <option key={l.code} value={l.code}>{l.native}</option>)}</select>; }
function LocalizedHome() { const { lang, c } = Route.useLoaderData(); return <div lang={lang} className="min-h-screen"><Header lang={lang} c={c}/><main><section className="hero-glow"><div className="mx-auto w-full max-w-6xl px-4 py-20 sm:px-6 lg:py-28"><p className="text-sm font-medium uppercase tracking-[0.2em] text-primary">{c.learn}</p><h1 className="mt-5 max-w-4xl text-5xl font-semibold leading-tight sm:text-6xl">{c.homeTitle}</h1><p className="mt-6 max-w-2xl text-lg text-muted-foreground">{c.intro}</p><div className="mt-8 flex flex-wrap gap-3"><Link to={`/${lang}/solver/3x3` as any} className="rounded-lg bg-primary px-5 py-3 text-sm font-medium text-primary-foreground">{c.solve3}</Link><Link to={`/${lang}/solver/2x2` as any} className="rounded-lg border border-border bg-background px-5 py-3 text-sm font-medium">{c.solve2}</Link></div></div></section><section className="mx-auto grid w-full max-w-6xl gap-4 px-4 py-16 sm:px-6 md:grid-cols-3"><Link to={`/${lang}/notation` as any} className="panel p-6 hover:border-primary"><RotateCw className="size-5 text-primary"/><h2 className="mt-4 text-xl font-semibold">{c.notationTitle}</h2><p className="mt-2 text-sm text-muted-foreground">{c.notationDescription}</p></Link><Link to={`/${lang}/timer` as any} className="panel p-6 hover:border-primary"><Clock3 className="size-5 text-primary"/><h2 className="mt-4 text-xl font-semibold">{c.timerTitle}</h2><p className="mt-2 text-sm text-muted-foreground">{c.timerDescription}</p></Link><div className="panel p-6"><h2 className="text-xl font-semibold">{c.tools}</h2><p className="mt-2 text-sm text-muted-foreground">{c.solver3Description}</p></div></section></main></div>; }
