import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Outlet, Link, createRootRouteWithContext, useRouter, HeadContent, Scripts } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import appCss from "../styles.css?url";
import { reportLovableError } from "../lib/lovable-error-reporting";
import { LANGUAGES } from "@/lib/i18n";

function NotFoundComponent() { return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-7xl font-bold text-foreground">404</h1><h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2><p className="mt-2 text-sm text-muted-foreground">The page you're looking for doesn't exist or has been moved.</p><div className="mt-6"><Link to="/" className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Go home</Link></div></div></div>; }
function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) { const router = useRouter(); useEffect(() => { reportLovableError(error, { boundary: "tanstack_root_error_component" }); }, [error]); return <div className="flex min-h-screen items-center justify-center bg-background px-4"><div className="max-w-md text-center"><h1 className="text-xl font-semibold text-foreground">This page didn't load</h1><p className="mt-2 text-sm text-muted-foreground">Something went wrong on our end. You can try refreshing or head back home.</p><div className="mt-6 flex justify-center gap-2"><button onClick={() => { router.invalidate(); reset(); }} className="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground">Try again</button><a href="/" className="rounded-md border border-input px-4 py-2 text-sm font-medium">Go home</a></div></div></div>; }

export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({
  head: () => ({ meta: [{ charSet: "utf-8" }, { name: "viewport", content: "width=device-width, initial-scale=1" }, { name: "author", content: "RubikSolver" }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "stylesheet", href: appCss }, { rel: "icon", href: "/favicon.ico", type: "image/x-icon" }, { rel: "preconnect", href: "https://fonts.googleapis.com" }, { rel: "preconnect", href: "https://fonts.gstatic.com" }, { rel: "stylesheet", href: "https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600&family=Space+Grotesk:wght@500;600;700&display=swap" }] }),
  shellComponent: RootShell, component: RootComponent, notFoundComponent: NotFoundComponent, errorComponent: ErrorComponent,
});
function RootShell({ children }: { children: ReactNode }) { return <html lang="en"><head><HeadContent /></head><body>{children}<Scripts /></body></html>; }
function RootComponent() { const { queryClient } = Route.useRouteContext(); return <QueryClientProvider client={queryClient}><div className="flex min-h-screen flex-col bg-background text-foreground"><header className="sticky top-0 z-20 border-b border-border/70 bg-background/85 backdrop-blur"><div className="mx-auto flex w-full max-w-6xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><Link to="/" className="font-display text-lg font-semibold tracking-tight">Rubik<span className="text-primary">Solver</span></Link><nav className="flex items-center gap-1 text-sm">{["2x2", "3x3"].map((slug) => <Link key={slug} to="/solver/$puzzle" params={{ puzzle: slug }} activeProps={{ className: "text-primary" }} className="rounded-lg px-3 py-1.5 text-muted-foreground transition hover:text-foreground">{slug}</Link>)}<Link to="/notation" activeProps={{ className: "text-primary" }} className="rounded-lg px-3 py-1.5 text-muted-foreground transition hover:text-foreground">Notation</Link><Link to="/timer" activeProps={{ className: "text-primary" }} className="rounded-lg px-3 py-1.5 text-muted-foreground transition hover:text-foreground">Timer</Link></nav><select aria-label="Language" defaultValue="en" onChange={e => { window.location.href = e.target.value === "en" ? "/" : `/${e.target.value}/`; }} className="rounded-lg border border-border bg-background px-2.5 py-1.5 text-sm">{LANGUAGES.map(l => <option key={l.code} value={l.code}>{l.native}</option>)}</select></div></header><main className="flex-1"><Outlet /></main></div></QueryClientProvider>; }
