import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/guides/what-is-cfop")({
  head: () => ({ meta: [{ title: "What Is CFOP? Rubik's Cube Speedcubing Method Explained | RubikSolver" }, { name: "description", content: "Learn what CFOP means in Rubik's Cube speedcubing: Cross, F2L, OLL, and PLL, plus how the method fits into 3x3 solving." }] }),
  component: CfopPage,
});

const stages = [["Cross", "Solve the four cross edges around the first-layer center while matching their side colors with the centers."], ["F2L", "First Two Layers combines a corner and its matching edge into a pair, then inserts that pair into its slot. This replaces much of the separate first-layer-corner and second-layer work used by beginner methods."], ["OLL", "Orientation of the Last Layer makes all stickers on the last-layer face point upward. Speedcubers learn OLL algorithms to handle different patterns efficiently."], ["PLL", "Permutation of the Last Layer moves the last-layer pieces into their correct positions while keeping their orientation solved. PLL completes the cube."]];

function CfopPage() { return <div className="mx-auto w-full max-w-4xl px-4 py-10 sm:px-6 sm:py-14"><Link to="/" className="text-sm text-muted-foreground hover:text-foreground">← Home</Link><header className="mt-8"><p className="text-sm font-medium uppercase tracking-[0.2em] text-primary">Speedcubing guide</p><h1 className="mt-2 text-4xl font-semibold sm:text-5xl">What Is CFOP?</h1><p className="mt-4 text-lg text-muted-foreground">CFOP is one of the most widely used methods for solving a 3×3 Rubik's Cube quickly. The name comes from its four stages: Cross, F2L, OLL, and PLL.</p></header><div className="mt-10 grid gap-5">{stages.map(([name,body],i) => <section key={name} className="panel p-6 sm:p-7"><div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-full bg-primary/15 text-sm font-semibold text-primary">{i+1}</span><h2 className="text-2xl font-semibold">{name}</h2></div><p className="mt-4 leading-7 text-muted-foreground">{body}</p></section>)}</div><section className="mt-8 panel p-6 sm:p-8"><h2 className="text-2xl font-semibold">CFOP vs. the beginner method</h2><p className="mt-2 leading-7 text-muted-foreground">The beginner method teaches the cube in manageable stages and is a great starting point. CFOP reorganizes the solve to reduce pauses and move count, especially through F2L and large sets of OLL and PLL algorithms.</p><Link to="/algorithms" className="mt-4 inline-flex text-sm font-medium text-primary underline">Explore Rubik's Cube algorithms →</Link></section></div> }
