/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlgorithmsRouteImport } from './routes/algorithms'
import { Route as NotationRouteImport } from './routes/notation'
import { Route as ScrambleGeneratorRouteImport } from './routes/scramble-generator'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as LangSplatRouteImport } from './routes/$lang.$'
import { Route as AlgorithmsF2lRouteImport } from './routes/algorithms/f2l'
import { Route as AlgorithmsOllRouteImport } from './routes/algorithms/oll'
import { Route as AlgorithmsPllRouteImport } from './routes/algorithms/pll'
import { Route as GuidesWhatIsCfopRouteImport } from './routes/guides/what-is-cfop'
import { Route as LearnHowToSolveARubiksCubeRouteImport } from './routes/learn/how-to-solve-a-rubiks-cube'
import { Route as SolverPuzzleRouteImport } from './routes/solver.$puzzle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsRoute = AlgorithmsRouteImport.update({
  id: '/algorithms',
  path: '/algorithms',
  getParentRoute: () => rootRouteImport,
} as any)
const NotationRoute = NotationRouteImport.update({
  id: '/notation',
  path: '/notation',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrambleGeneratorRoute = ScrambleGeneratorRouteImport.update({
  id: '/scramble-generator',
  path: '/scramble-generator',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangSplatRoute = LangSplatRouteImport.update({
  id: '/$lang/$',
  path: '/$lang/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgorithmsF2lRoute = AlgorithmsF2lRouteImport.update({
  id: '/f2l',
  path: '/f2l',
  getParentRoute: () => AlgorithmsRoute,
} as any)
const AlgorithmsOllRoute = AlgorithmsOllRouteImport.update({
  id: '/oll',
  path: '/oll',
  getParentRoute: () => AlgorithmsRoute,
} as any)
const AlgorithmsPllRoute = AlgorithmsPllRouteImport.update({
  id: '/pll',
  path: '/pll',
  getParentRoute: () => AlgorithmsRoute,
} as any)
const GuidesWhatIsCfopRoute = GuidesWhatIsCfopRouteImport.update({
  id: '/guides/what-is-cfop',
  path: '/guides/what-is-cfop',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnHowToSolveARubiksCubeRoute =
  LearnHowToSolveARubiksCubeRouteImport.update({
    id: '/learn/how-to-solve-a-rubiks-cube',
    path: '/learn/how-to-solve-a-rubiks-cube',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolverPuzzleRoute = SolverPuzzleRouteImport.update({
  id: '/solver/$puzzle',
  path: '/solver/$puzzle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRouteWithChildren
  '/notation': typeof NotationRoute
  '/scramble-generator': typeof ScrambleGeneratorRoute
  '/timer': typeof TimerRoute
  '/$lang/$': typeof LangSplatRoute
  '/algorithms/f2l': typeof AlgorithmsF2lRoute
  '/algorithms/oll': typeof AlgorithmsOllRoute
  '/algorithms/pll': typeof AlgorithmsPllRoute
  '/guides/what-is-cfop': typeof GuidesWhatIsCfopRoute
  '/learn/how-to-solve-a-rubiks-cube': typeof LearnHowToSolveARubiksCubeRoute
  '/solver/$puzzle': typeof SolverPuzzleRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRouteWithChildren
  '/notation': typeof NotationRoute
  '/scramble-generator': typeof ScrambleGeneratorRoute
  '/timer': typeof TimerRoute
  '/$lang/$': typeof LangSplatRoute
  '/algorithms/f2l': typeof AlgorithmsF2lRoute
  '/algorithms/oll': typeof AlgorithmsOllRoute
  '/algorithms/pll': typeof AlgorithmsPllRoute
  '/guides/what-is-cfop': typeof GuidesWhatIsCfopRoute
  '/learn/how-to-solve-a-rubiks-cube': typeof LearnHowToSolveARubiksCubeRoute
  '/solver/$puzzle': typeof SolverPuzzleRoute
  '/$lang': typeof LangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algorithms': typeof AlgorithmsRouteWithChildren
  '/notation': typeof NotationRoute
  '/scramble-generator': typeof ScrambleGeneratorRoute
  '/timer': typeof TimerRoute
  '/$lang/$': typeof LangSplatRoute
  '/algorithms/f2l': typeof AlgorithmsF2lRoute
  '/algorithms/oll': typeof AlgorithmsOllRoute
  '/algorithms/pll': typeof AlgorithmsPllRoute
  '/guides/what-is-cfop': typeof GuidesWhatIsCfopRoute
  '/learn/how-to-solve-a-rubiks-cube': typeof LearnHowToSolveARubiksCubeRoute
  '/solver/$puzzle': typeof SolverPuzzleRoute
  '/$lang/': typeof LangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algorithms'
    | '/notation'
    | '/scramble-generator'
    | '/timer'
    | '/$lang/$'
    | '/algorithms/f2l'
    | '/algorithms/oll'
    | '/algorithms/pll'
    | '/guides/what-is-cfop'
    | '/learn/how-to-solve-a-rubiks-cube'
    | '/solver/$puzzle'
    | '/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algorithms'
    | '/notation'
    | '/scramble-generator'
    | '/timer'
    | '/$lang/$'
    | '/algorithms/f2l'
    | '/algorithms/oll'
    | '/algorithms/pll'
    | '/guides/what-is-cfop'
    | '/learn/how-to-solve-a-rubiks-cube'
    | '/solver/$puzzle'
    | '/$lang'
  id:
    | '__root__'
    | '/'
    | '/algorithms'
    | '/notation'
    | '/scramble-generator'
    | '/timer'
    | '/$lang/$'
    | '/algorithms/f2l'
    | '/algorithms/oll'
    | '/algorithms/pll'
    | '/guides/what-is-cfop'
    | '/learn/how-to-solve-a-rubiks-cube'
    | '/solver/$puzzle'
    | '/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgorithmsRoute: typeof AlgorithmsRouteWithChildren
  NotationRoute: typeof NotationRoute
  ScrambleGeneratorRoute: typeof ScrambleGeneratorRoute
  TimerRoute: typeof TimerRoute
  LangSplatRoute: typeof LangSplatRoute
  GuidesWhatIsCfopRoute: typeof GuidesWhatIsCfopRoute
  LearnHowToSolveARubiksCubeRoute: typeof LearnHowToSolveARubiksCubeRoute
  SolverPuzzleRoute: typeof SolverPuzzleRoute
  LangIndexRoute: typeof LangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms': {
      id: '/algorithms'
      path: '/algorithms'
      fullPath: '/algorithms'
      preLoaderRoute: typeof AlgorithmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notation': {
      id: '/notation'
      path: '/notation'
      fullPath: '/notation'
      preLoaderRoute: typeof NotationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scramble-generator': {
      id: '/scramble-generator'
      path: '/scramble-generator'
      fullPath: '/scramble-generator'
      preLoaderRoute: typeof ScrambleGeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/$': {
      id: '/$lang/$'
      path: '/$lang/$'
      fullPath: '/$lang/$'
      preLoaderRoute: typeof LangSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algorithms/f2l': {
      id: '/algorithms/f2l'
      path: '/f2l'
      fullPath: '/algorithms/f2l'
      preLoaderRoute: typeof AlgorithmsF2lRouteImport
      parentRoute: typeof AlgorithmsRoute
    }
    '/algorithms/oll': {
      id: '/algorithms/oll'
      path: '/oll'
      fullPath: '/algorithms/oll'
      preLoaderRoute: typeof AlgorithmsOllRouteImport
      parentRoute: typeof AlgorithmsRoute
    }
    '/algorithms/pll': {
      id: '/algorithms/pll'
      path: '/pll'
      fullPath: '/algorithms/pll'
      preLoaderRoute: typeof AlgorithmsPllRouteImport
      parentRoute: typeof AlgorithmsRoute
    }
    '/guides/what-is-cfop': {
      id: '/guides/what-is-cfop'
      path: '/guides/what-is-cfop'
      fullPath: '/guides/what-is-cfop'
      preLoaderRoute: typeof GuidesWhatIsCfopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/how-to-solve-a-rubiks-cube': {
      id: '/learn/how-to-solve-a-rubiks-cube'
      path: '/learn/how-to-solve-a-rubiks-cube'
      fullPath: '/learn/how-to-solve-a-rubiks-cube'
      preLoaderRoute: typeof LearnHowToSolveARubiksCubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solver/$puzzle': {
      id: '/solver/$puzzle'
      path: '/solver/$puzzle'
      fullPath: '/solver/$puzzle'
      preLoaderRoute: typeof SolverPuzzleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AlgorithmsRouteChildren {
  AlgorithmsF2lRoute: typeof AlgorithmsF2lRoute
  AlgorithmsOllRoute: typeof AlgorithmsOllRoute
  AlgorithmsPllRoute: typeof AlgorithmsPllRoute
}

const AlgorithmsRouteChildren: AlgorithmsRouteChildren = {
  AlgorithmsF2lRoute: AlgorithmsF2lRoute,
  AlgorithmsOllRoute: AlgorithmsOllRoute,
  AlgorithmsPllRoute: AlgorithmsPllRoute,
}

const AlgorithmsRouteWithChildren = AlgorithmsRoute._addFileChildren(
  AlgorithmsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgorithmsRoute: AlgorithmsRouteWithChildren,
  NotationRoute: NotationRoute,
  ScrambleGeneratorRoute: ScrambleGeneratorRoute,
  TimerRoute: TimerRoute,
  LangSplatRoute: LangSplatRoute,
  GuidesWhatIsCfopRoute: GuidesWhatIsCfopRoute,
  LearnHowToSolveARubiksCubeRoute: LearnHowToSolveARubiksCubeRoute,
  SolverPuzzleRoute: SolverPuzzleRoute,
  LangIndexRoute: LangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
